Class "Auth" not found
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(15): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(86): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(17): view('home.index')
#3 {main}Class "Auth" not found
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(15): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(86): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(17): view('home.index')
#3 {main}Class "Auth" not found
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(15): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(86): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(17): view('home.index')
#3 {main}[2025-05-16 16:42:55] ERROR: Class "Auth" not found
File: C:\xampp\htdocs\intermodular\resources\views\layouts\app.php Line: 12
Stack trace:
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(47): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(92): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(41): view('home.index')
#3 {main}

[2025-05-16 16:44:03] ERROR: Class "Auth" not found
File: C:\xampp\htdocs\intermodular\resources\views\layouts\app.php Line: 12
Stack trace:
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(47): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(92): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(41): view('home.index')
#3 {main}

[2025-05-16 16:44:22] ERROR: Class "Auth" not found
File: C:\xampp\htdocs\intermodular\resources\views\layouts\app.php Line: 12
Stack trace:
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(47): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(92): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(41): view('home.index')
#3 {main}

[2025-05-16 16:44:25] ERROR: Class "Auth" not found
File: C:\xampp\htdocs\intermodular\resources\views\layouts\app.php Line: 12
Stack trace:
#0 C:\xampp\htdocs\intermodular\app\Core\Response.php(47): require()
#1 C:\xampp\htdocs\intermodular\app\Core\helpers.php(92): App\Core\Response::view('home.index', Array)
#2 C:\xampp\htdocs\intermodular\public\index.php(41): view('home.index')
#3 {main}

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for sql111.infinityfree.com failed: Host desconocido. 
#0 C:\xampp\htdocs\intermodular\app\Core\DB.php(19): PDO->__construct('mysql:host=sql1...', 'if0_38694634', Object(SensitiveParameterValue))
#1 C:\xampp\htdocs\intermodular\app\Core\DB.php(97): App\Core\DB::connection()
#2 C:\xampp\htdocs\intermodular\app\Core\DB.php(33): App\Core\DB::prepare('SELECT * FROM c...', Array)
#3 C:\xampp\htdocs\intermodular\app\Core\DB.php(66): App\Core\DB::select('App\\Models\\Clie...', 'SELECT * FROM c...', Array)
#4 C:\xampp\htdocs\intermodular\app\Core\QueryBuilder.php(114): App\Core\DB::selectOne('App\\Models\\Clie...', 'SELECT * FROM c...', Array)
#5 C:\xampp\htdocs\intermodular\app\Core\Auth.php(16): App\Core\QueryBuilder->first()
#6 C:\xampp\htdocs\intermodular\app\Http\Controllers\AuthController.php(24): App\Core\Auth::attempt(Array)
#7 C:\xampp\htdocs\intermodular\public\auth\login.php(30): App\Http\Controllers\AuthController->login(Object(App\Core\Request))
#8 {main}SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\intermodular\app\Core\DB.php(19): PDO->__construct('mysql:host=loca...', 'root', Object(SensitiveParameterValue))
#1 C:\xampp\htdocs\intermodular\app\Core\DB.php(97): App\Core\DB::connection()
#2 C:\xampp\htdocs\intermodular\app\Core\DB.php(33): App\Core\DB::prepare('SELECT * FROM c...', Array)
#3 C:\xampp\htdocs\intermodular\app\Core\DB.php(66): App\Core\DB::select('App\\Models\\Clie...', 'SELECT * FROM c...', Array)
#4 C:\xampp\htdocs\intermodular\app\Core\QueryBuilder.php(114): App\Core\DB::selectOne('App\\Models\\Clie...', 'SELECT * FROM c...', Array)
#5 C:\xampp\htdocs\intermodular\app\Core\Auth.php(16): App\Core\QueryBuilder->first()
#6 C:\xampp\htdocs\intermodular\app\Http\Controllers\AuthController.php(24): App\Core\Auth::attempt(Array)
#7 C:\xampp\htdocs\intermodular\public\auth\login.php(30): App\Http\Controllers\AuthController->login(Object(App\Core\Request))
#8 {main}SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\intermodular\app\Core\DB.php(19): PDO->__construct('mysql:host=loca...', 'root', Object(SensitiveParameterValue))
#1 C:\xampp\htdocs\intermodular\app\Core\DB.php(97): App\Core\DB::connection()
#2 C:\xampp\htdocs\intermodular\app\Core\DB.php(33): App\Core\DB::prepare('SELECT * FROM c...', Array)
#3 C:\xampp\htdocs\intermodular\app\Core\DB.php(66): App\Core\DB::select('App\\Models\\Clie...', 'SELECT * FROM c...', Array)
#4 C:\xampp\htdocs\intermodular\app\Core\QueryBuilder.php(114): App\Core\DB::selectOne('App\\Models\\Clie...', 'SELECT * FROM c...', Array)
#5 C:\xampp\htdocs\intermodular\app\Core\Auth.php(16): App\Core\QueryBuilder->first()
#6 C:\xampp\htdocs\intermodular\app\Http\Controllers\AuthController.php(24): App\Core\Auth::attempt(Array)
#7 C:\xampp\htdocs\intermodular\public\auth\login.php(30): App\Http\Controllers\AuthController->login(Object(App\Core\Request))
#8 {main}